version: '3.1'

services:

  db:
    image: postgres:9.6.15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: o8e4v7wjnt39w82380947n5v209
    ports:
      - "5432:5432"
      
  redis:
    build: redis
    ports:
      - "6379:6379"