﻿version: '3.1'
services:

  nxplx-database:
    image: postgres:12-alpine
    volumes:
      - /srv/nxplx/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: o8e4v7wjnt39w82380947n5v209

  nxplx-cache:
    image: redis:5.0.6-alpine
    command: redis-server --requirepass 4f9o87b6hw498f6w4g5764ohlaglafv94ab68lbvoa9487b

  nxplx-webapi:
    image: mrosenbjerg/nxplx-webapi
    environment:
      REDIS_PASSWORD: 4f9o87b6hw498f6w4g5764ohlaglafv94ab68lbvoa9487b
      POSTGRES_PASSWORD: o8e4v7wjnt39w82380947n5v209
      NXPLX_PROBE_TOKEN: 45nv8239457w34589vngb7839b7v3452v903458457eg
    volumes:
      - /srv/nxplx/webapi:/app/data
      - /mymedia:/media:ro
    depends_on:
      - nxplx-database
      - nxplx-cache
    ports:
      - "5353:5353"