name: Build multi-arch docker images

on:
  pull_request:
    branches: release

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Login to Docker
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build AMD64 image
        run: |
          docker buildx build \
            --build-arg tmdbApiKey=${{ secrets.TMDB_API_KEY }} \
            --output "type=image,push=true" \
            --tag mrosenbjerg/nxplx-webapi:amd64 \
            --tag mrosenbjerg/nxplx-webapi:latest \
            --file ./docker/gh-build/amd64/Dockerfile ./docker/gh-build/amd64
      -
        name: Build ARM32v7 image
        run: |
          docker buildx build \
            --build-arg tmdbApiKey=${{ secrets.TMDB_API_KEY }} \
            --output "type=image,push=true" \
            --tag mrosenbjerg/nxplx-webapi:arm32v7 \
            --tag mrosenbjerg/nxplx-webapi:latest \
            --file ./docker/gh-build/arm32v7/Dockerfile ./docker/gh-build/arm32v7
      -
        name: Build ARM64v8 image
        run: |
          docker buildx build \
            --build-arg tmdbApiKey=${{ secrets.TMDB_API_KEY }} \
            --output "type=image,push=true" \
            --tag mrosenbjerg/nxplx-webapi:arm64v8 \
            --tag mrosenbjerg/nxplx-webapi:latest \
            --file ./docker/gh-build/arm64v8/Dockerfile ./docker/gh-build/arm64v8
