name: Build multi-arch docker images

on:
  pull_request:
    branches: release

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build AMD64
        run: |
          docker buildx build \
            --build-arg tmdbApiKey=${{ secrets.TMDB_API_KEY }} \
            --output "type=image,push=false" \
            --file ./docker/gh-build/amd64/Dockerfile ./docker/gh-build/amd64
      -
        name: Build ARM32v7
        run: |
          docker buildx build \
            --build-arg tmdbApiKey=${{ secrets.TMDB_API_KEY }} \
            --output "type=image,push=false" \
            --file ./docker/gh-build/arm32v7/Dockerfile ./docker/gh-build/arm32v7
      -
        name: Build ARM64
        run: |
          docker buildx build \
            --build-arg tmdbApiKey=${{ secrets.TMDB_API_KEY }} \
            --output "type=image,push=false" \
            --file ./docker/gh-build/arm64v8/Dockerfile ./docker/gh-build/arm64v8
