name: SonarCloud Scan

on: 
  push:
    branches: main

jobs:
  sonarScan:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@master
    -
      name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      uses: sonarsource/sonarcloud-github-action@master
